### ISSUE TITLE
请问要哪个版本才能看到tags

### ISSUE THREAD

**Issue by fifthszsu** [awehook/react-mindmap#10]
![image](https://user-images.githubusercontent.com/46641737/110920786-c4613e00-8358-11eb-8030-5517fc5d8369.png)
我现在用"@blink-mind/renderer-react": "0.0.20-beta.6", 这个版本，但是并没有看到有tags

**Comment by fifthszsu** [comment]
"@blink-mind/core": "0.0.20-beta.6",
    "@blink-mind/icons": "0.0.20-beta.6",
    "@blink-mind/plugin-json-serializer": "0.0.20-beta.6",
    "@blink-mind/plugin-rich-text-editor": "0.0.20-beta.6",
    "@blink-mind/plugin-theme-selector": "0.0.20-beta.6",
    "@blink-mind/plugin-topology-diagram": "0.0.20-beta.6",
    "@blink-mind/plugins": "0.0.20-beta.6",
    "@blink-mind/renderer-react": "0.0.20-beta.6",

这些是我的依赖包

**Comment by awehook** [comment]
v0.0.20-beta.12
