### ISSUE TITLE
可否添加labels功能？

### ISSUE THREAD

**Issue by huajianmao** [awehook/react-mindmap#5]
允许为每个Topic添加Labels功能，类比xmind中的labels，如下图：
![image](https://user-images.githubusercontent.com/1352072/80293930-9998e600-8796-11ea-89ed-c48c0d9b3403.png)

**Comment by awehook** [comment]
可否仔细描述下需求

**Comment by huajianmao** [comment]
@awehook 为Topic添加labels

**Comment by awehook** [comment]
我不知道你说的labels是什么意思，如果是表示tag的话，现在是有的
