### ISSUE TITLE
used <Mindmap /> component imported in my local project, but encountered CSS issue

### ISSUE THREAD

**Issue by ramu-thinkthroo** [awehook/react-mindmap#6]
Hi, thank you for this awesome project. I really like it. I am writing this issue to see what could be it that I am missing since the component is failing to load the necessary css to keep the same as in demos, I have attached the screenshots FYI. I really appreciate it, if you could help me understand the missing CSS import in my case, it can be helpful for others that might encounter this problem as well.
<img width="1195" alt="Screenshot 2020-04-26 at 3 15 27 PM" src="https://user-images.githubusercontent.com/55570508/80304005-2e203a00-87d1-11ea-9ba1-c4de8341ba09.png"> 
this one is from my localhost in my project

<img width="1439" alt="Screenshot 2020-04-26 at 3 19 31 PM" src="https://user-images.githubusercontent.com/55570508/80304043-60319c00-87d1-11ea-958a-462cbbdaddaf.png">
 this one is from this repo, cloned and ran locally. the main problem as you can see in these 2 images is that width and height in my local project are very huge, I am suspecting there is a CSS import that I am missing. But I looked at it all, I copied the same folder and components used in this repo, but unsuccessful to fix this issue. Please look into it

**Comment by awehook** [comment]
I need you to provide the code and I can debug it.

**Comment by ramu-thinkthroo** [comment]
ok, thanks for the reply, I will share the repo details with you soon here.

**Comment by thinkThroo** [comment]
thanks for replying, btw.

**Comment by ramu-thinkthroo** [comment]
https://github.com/thinkThroo/react-app-blinkmind-demo.git hey, here is link to repo that produced this CSS effects OFF results, what surprised me is that the "className" in case of working example is different from the one in CSS failed view, here is a screenshot
this one works fine, from github pages
<img width="1439" alt="Screenshot 2020-04-26 at 5 19 13 PM" src="https://user-images.githubusercontent.com/55570508/80306671-56646480-87e2-11ea-8703-23e4d831ac91.png">
notice the className **_ZmjGK_** pointed by arrow
here is a screenshot from CSS issue build
<img width="1439" alt="Screenshot 2020-04-26 at 5 19 49 PM" src="https://user-images.githubusercontent.com/55570508/80306695-7b58d780-87e2-11ea-8a9d-c06cd2263e67.png">
notice that className is different pointed by the arrow.
the repo has 2 folders
1. css-issue-newi-formed
2. working-example
you can start the local host, by doing _npm install_ , **npm run start** in both the folders.

the one which had css issue has react-redux configured. Would it have any influence in generating classnames and importing CSS? please take a look.

**Comment by awehook** [comment]
You forgot to set the dimension of the mindmap.

html {
  width: 100%;
  height: 100%;
}

body {
  width: 100%;
  height: 100%;
  margin: 0 auto;
}

.mindmap {
  width: 100vw;
  height: calc(100vh - 36px);
}

#root {
  position: fixed;
  left: 0;
  top: 0;
  width: 100%;
  height: 100%;
}

**Comment by ramu-thinkthroo** [comment]
Appreciate your insight, but apparently adding that CSS above did not fix the CSS issue. :(
<img width="1439" alt="Screenshot 2020-04-26 at 7 51 50 PM" src="https://user-images.githubusercontent.com/55570508/80310310-8e29d700-87f7-11ea-86a3-1686321420c3.png">
<img width="1439" alt="Screenshot 2020-04-26 at 7 51 33 PM" src="https://user-images.githubusercontent.com/55570508/80310311-92ee8b00-87f7-11ea-8355-9a48a4f442cf.png">

**Comment by ramu-thinkthroo** [comment]
please notice the class names differences between the two images posted above, also had there been any change made to width and height using dev tools, it just keeps increasing in number.

**Comment by awehook** [comment]
![image](https://user-images.githubusercontent.com/43373978/80312773-ce9a4c80-8819-11ea-9d7c-4163862d5535.png)

**Comment by awehook** [comment]
![image](https://user-images.githubusercontent.com/43373978/80312895-67c96300-881a-11ea-918a-1892d2d3a61c.png)
You can find the fix commit  in https://github.com/awehook/react-app-blinkmind-demo

**Comment by ramu-thinkthroo** [comment]
I am sorry, I cloned the repo https://github.com/awehook/react-app-blinkmind-demo , started the server inside 'css-issue-new-id-formed' dir, the height and width css you have added are seen, but that did not completely fix CSS issue, were you able to see the view with the right CSS fix when server run from  'css-issue-new-id-formed' dir?
the view is like this:
<img width="1439" alt="Screenshot 2020-04-26 at 9 44 39 PM" src="https://user-images.githubusercontent.com/55570508/80313221-2aa7a580-8807-11ea-8ebd-b70d154dc2e1.png">

**Comment by awehook** [comment]
I confirm that I have no problem in my local environment.

**Comment by ramu-thinkthroo** [comment]
okay, thanks. I will post the update if it has been fixed in my case. Appreciate your time.

**Comment by ramu-thinkthroo** [comment]
How are the classnames generated for the react-mindmap? is it random or there is some predefined classnames? as you can see above the one with the CSS off has different classname, I checked your github pages and and react-mindmap repo, they have the same className for the element right under the div element with class="mindmap" with child node class name as `ZjmGK` but in my case it shows up as something like `hxWmkW`

**Comment by ramu-thinkthroo** [comment]
I confirm that this has happened due to some unknown css import that has caused this issue. closing the issue.
