### ISSUE TITLE
yarn start后无法edit note

### ISSUE THREAD

**Issue by SteveY4ng** [awehook/react-mindmap#7]
您好！当我在本地启动此项目后，右键topic去edit note，但是报错如下，无法进行编辑。不知道能否帮助解决。谢谢！
<img width="943" alt="2" src="https://user-images.githubusercontent.com/40466358/80344182-bc5ff300-8899-11ea-876f-f3cf1e535f81.png">

**Comment by tanghui315** [comment]
同问这个问题

**Comment by awehook** [comment]
react-mindmap 只是@blink-mind库的一个示例，这里面使用的@blink-mind 不是最新版本，后面精力主要放在electron客户端blink-mind-desktop 这个项目了，见谅
